#!/usr/bin/env zsh

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

brew install nvm
brew install bat
brew install jq
brew install go
brew install gh
brew install uv
brew install difftastic
brew install mergiraf
brew install --cask raycast
brew install --cask zed
brew install --cask warp
brew install --cask obsidian

# Have Git use mergiraf by default
git config --global merge.mergiraf.name mergiraf
git config --global merge.mergiraf.driver 'mergiraf merge --git %O %A %B -s %S -x %X -y %Y -p %P -l %L'

# Add mergiraf to the global gitattributes file if it's not already there
if ! grep -q '* merge=mergiraf' ~/.config/git/attributes; then
  echo '* merge=mergiraf' >> ~/.config/git/attributes
fi

# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

if [ ! -d "$HOME/.local-scripts" ]
then
  mkdir "$HOME/.local-scripts"
  touch "$HOME/.local-scripts/general.zsh"
fi

git config --global user.name "Christopher Bradshaw"
git config --global user.email "chris.kofox@gmail.com"

chsh -s $(which zsh)

if [ ! -d "$HOME/Git" ]
then
  mkdir -p "$HOME/Git/module-edits"
fi

if [ ! -d "$HOME/Git/kitsune-settings" ]
then
  git clone https://github.com/kitsune7/kitsune-settings.git "$HOME/Git/kitsune-settings"
fi

# Disable the keyboard layout indicator (language indicator)
defaults write kCFPreferencesAnyApplication TSMLanguageIndicatorEnabled 0
echo "Language indicator has been disabled. This change requires a system restart to take effect."

# Add Dvorak keyboard layout
if defaults read com.apple.HIToolbox AppleEnabledInputSources | grep -q "Dvorak"
then
  echo "Dvorak keyboard layout is already added."
else
  echo "Adding Dvorak keyboard layout..."
  defaults write com.apple.HIToolbox AppleInputSourceHistory -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>16777219</integer><key>KeyboardLayout Name</key><string>Dvorak</string></dict>'

  # Update enabled input sources
  defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>16777219</integer><key>KeyboardLayout Name</key><string>Dvorak</string></dict>'

  # Keep Mac Desktops from re-arranging themselves
  defaults write com.apple.dock "mru-spaces" -bool "false" && killall Dock

  # Restart the system preferences daemon
  killall cfprefsd

  echo "Dvorak keyboard layout has been added."
  echo "You may need to log out and log back in for the changes to take effect."
fi

# Set up kitsune-mcp-router
if [ ! -f /usr/local/bin/kitsune-mcp-router ]
then
  sudo touch /usr/local/bin/kitsune-mcp-router
  sudo chown $USER /usr/local/bin/kitsune-mcp-router
  echo "$(cat << EOF
  #!/usr/bin/env bash
  "\${SETTINGS_DIR}/ai/mcp-router.sh" \$@
  EOF
  )" > /usr/local/bin/kitsune-mcp-router
  chmod +x /usr/local/bin/kitsune-mcp-router
fi

$HOME/Git/kitsune-settings/sync

setup-icloud-dir

echo "Do you want to set up a new SSH key for the system? (y/n)"
read response
if [ "$response" = "y" ]
then
  new-ssh-key
else
  echo "No SSH key will be set up. You can always set one up later by running \"new-ssh-key\"."
fi
