#!/bin/bash
shopt -s extglob
shopt -s dotglob

alias showInstallScriptUsage='usage: sync [-h | [-q]]'
overwrite=""
quiet=""

# https://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":hq" option; do
  case "${option}" in
    h) # Help
      showInstallScriptUsage
    ;;
    q)
      quiet="true"
    ;;
    \?)
      error "Unexpected option ${option}"
      showInstallScriptUsage
    ;;
  esac
done

function log () {
  if [[ ! "$quiet" ]]; then
    echo "$1"
  fi
}

function getCpOptions () {
  options=$(echo "-$([[ -z $overwrite ]] && echo 'i')$([[ -z $quiet ]] && echo 'v')")
  [[ $options != '-' ]] && echo "$options"
}

function copyFiles () {
  srcDir=$1
  destDir=$2
  for i in "$srcDir"/*; do
    file=$(basename -- "$i")
    rsync -a --progress "$srcDir/$file" "$destDir"
  done
}

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

copyFiles "$currentDir/home-settings" "$HOME"
copyFiles "$currentDir/oh-my-zsh-custom" "$HOME/.oh-my-zsh/custom"
rsync -a --progress "$currentDir/other-settings/com.googlecode.iterm2.plist" "${HOME}/Library/Preferences"
rsync -a --progress "$currentDir/other-settings/mcp.json" "$HOME/.cursor/mcp.json"

log "Finished syncing settings"
exit 0
