#!/bin/bash
shopt -s extglob
shopt -s dotglob

alias showInstallScriptUsage='usage: sync [-h | [-q]]'
overwrite=""
quiet=""

# https://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":hq" option; do
  case "${option}" in
    h) # Help
      showInstallScriptUsage
    ;;
    q)
      quiet="true"
    ;;
    \?)
      error "Unexpected option ${option}"
      showInstallScriptUsage
    ;;
  esac
done

function log () {
  if [[ ! "$quiet" ]]; then
    echo "$1"
  fi
}

function getCpOptions () {
  options=$(echo "-$([[ -z $overwrite ]] && echo 'i')$([[ -z $quiet ]] && echo 'v')")
  [[ $options != '-' ]] && echo "$options"
}

function copyFiles () {
  srcDir=$1
  destDir=$2
  for i in "$srcDir"/*; do
    file=$(basename -- "$i")
    rsync -a --progress "$srcDir/$file" "$destDir"
  done
}

function sync-newest () {
  file1="$1"
  file2="$2"

  if [[ ! -e "$file1" ]] && [[ ! -e "$file2" ]]; then
    echo "Neither file exists"
    return 1
  elif [[ ! -e "$file1" ]]; then
    cp "$file2" "$file1"
    echo "Copied $file2 to $file1 (file1 didn't exist)"
  elif [[ ! -e "$file2" ]]; then
    cp "$file1" "$file2"
    echo "Copied $file1 to $file2 (file2 didn't exist)"
  elif [[ "$file1" -nt "$file2" ]]; then
    cp "$file1" "$file2"
    echo "Copied newer $file1 to $file2"
  elif [[ "$file2" -nt "$file1" ]]; then
    cp "$file2" "$file1"
    echo "Copied newer $file2 to $file1"
  else
    echo "Files are already in sync"
  fi
}

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

copyFiles "$currentDir/home-settings" "$HOME"
copyFiles "$currentDir/oh-my-zsh-custom" "$HOME/.oh-my-zsh/custom"
copyFiles "$currentDir/other-settings/.claude" "$HOME/.claude"
copyFiles "$currentDir/other-settings/zed" "$HOME/.config/zed"
sync-newest "$currentDir/other-settings/zed/settings.json" "$HOME/.config/zed/settings.json"
sync-newest "$currentDir/other-settings/zed/snippets" "$HOME/.config/zed/snippets"
rsync -a --progress "$currentDir/other-settings/com.googlecode.iterm2.plist" "${HOME}/Library/Preferences"

log "Finished syncing settings"
exit 0
