#!/bin/bash
shopt -s extglob
shopt -s dotglob

alias showInstallScriptUsage='usage: sync [-h | [-q]]'
overwrite=""
quiet=""

# https://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":hq" option; do
  case "${option}" in
    h) # Help
      showInstallScriptUsage
    ;;
    q)
      quiet="true"
    ;;
    \?)
      error "Unexpected option ${option}"
      showInstallScriptUsage
    ;;
  esac
done

function log () {
  if [[ ! "$quiet" ]]; then
    echo "$1"
  fi
}

function getCpOptions () {
  options=$(echo "-$([[ -z $overwrite ]] && echo 'i')$([[ -z $quiet ]] && echo 'v')")
  [[ $options != '-' ]] && echo "$options"
}

function copyFiles () {
  srcDir=$1
  destDir=$2
  for i in "$srcDir"/*; do
    file=$(basename -- "$i")
    rsync -a --progress "$srcDir/$file" "$destDir"
  done
}

function sync-newest () {
  file1="$1"
  file2="$2"

  # Copy from file1 to file2 if file1 is newer
  rsync -u "$file1" "$file2" 2>/dev/null

  # Copy from file2 to file1 if file2 is newer
  rsync -u "$file2" "$file1" 2>/dev/null
}

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

copyFiles "$currentDir/home-settings" "$HOME"
copyFiles "$currentDir/oh-my-zsh-custom" "$HOME/.oh-my-zsh/custom"
copyFiles "$currentDir/other-settings/.claude" "$HOME/.claude"
copyFiles "$currentDir/other-settings/zed" "$HOME/.config/zed"
sync-newest "$currentDir/other-settings/zed/settings.json" "$HOME/.config/zed/settings.json"
sync-newest "$currentDir/other-settings/zed/snippets" "$HOME/.config/zed/snippets"
rsync -a --progress "$currentDir/other-settings/com.googlecode.iterm2.plist" "${HOME}/Library/Preferences"

log "Finished syncing settings"
exit 0
